### ISSUE TITLE
Best grepWin alternative tool for Linux.

### ISSUE THREAD

**Issue by abuhenasobuj** [facelessuser/Rummage#105]
Same as you. 
I wanted (find) a best similar tool in Linux like grepWin. And finally found **Rummage**.
Recently I installed it & feel like grepWin.

If you permit me then I'll try to add this into alternativeto.net site.

**Comment by facelessuser** [comment]
> Same as you.
I wanted (find) a best similar tool in Linux like grepWin. And finally found Rummage.
Recently I installed it & feel like grepWin.

Yeah, it's not without its weaknesses, but I honestly use Rummage now more than grepWin on Windows and exclusively on Mac and Linux.  I'm glad that other people have found it useful. It's always nice to hear that I'm not the only one who finds the grep tools lacking elsewhere 🙂 .  I guess there are a number of command line warriors out there with no need for a GUI grep, but I still like a nice GUI when searching folders of files.

> If you permit me then I'll try to add this into alternativeto.net site.

I'm okay with that.  It's purpose was to be an alternative.  So if others find it suitable as an alternative, I don't mind people sharing that.

**Comment by abuhenasobuj** [comment]
Software link added [Rummage Alternatives and Similar Software - AlternativeTo.net](https://alternativeto.net/software/rummage-python/)

**Comment by facelessuser** [comment]
Thanks!
