### ISSUE TITLE
Windows 10 "Python has stopped working" on close

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#142]
For some reason, only on Windows, and I believe on windows 10, on close you can get an annoying "Python has stopped working" dialog. No other information is provided. This seems specifically to occur when running it via `pythonw -m rummage`.  Maybe it is related to anything being logged to stdout?  Not sure.  Regardless it is annoying. This doesn't seem to occur if you run it directly via `rummage` or even with `python -m rummage`.

It may be a general WxPython or maybe Python bug, or it may be related to something we are doing, but I've had a difficult time isolating the issue.

I want to track this to remind me to look into it.

**Comment by facelessuser** [comment]
Just a note to myself, I should probably add in the documentation a notice that if running with `python -m rummage` (or with `pythonw -m rummage`), that Rummage will pick up and include Python libraries in the CWD if they happen to match the name of the libraries it is looking for.  Using the `rummage` command script is preferable (but `python -m` is great during development when I want to test the local checkout 😉).

**Comment by facelessuser** [comment]
I'm starting to think the reason we get this is that we exit, but something is still not quite quitting in WxPython on Windows.

It seems calling `wx.Exit()` before calling `sys.exit(0)` causes this issue to go away.  While `wx.Exit()` works, it is not ideal as it is masking the issue.  I'd like to understand why I get this and properly resolve it, but `wx.Exit()` at least will force everything to quit for now.  Hopefully I can get to the bottom of this and not have to do `wx.Exit()` which mentions in the documentation:

```
Should only be used in an emergency: normally the top-level frame should be deleted (after deleting all other frames) to terminate the application. See wx.CloseEvent and wx.App.
```

Since this works, it is clearly pointing to something not getting cleared up.  Since I don't see issues on Mac or Linux, this leads me to believe it is something Windows specific.

**Comment by facelessuser** [comment]
This is not specific to `pythonw` or even `python -m`.  This does seem specific to Windows 10 as I've never seen this on Windows 7, but I used to be able to reproduce this my work Windows laptop, now I can't.  I can only reproduce this on my work Windows Desktop.  This may be an environment issue.  Or the classic "reboot the computer" to fix the issue. Sigh....Windows.  This is not going to be critical for the next release.  I'll just leave it open until I finally have some kind of epiphany.

As mentioned before, `wx.Exit()` will skip over the issue, but I seem to be the only one who ever sees it, I can't even see it on more than one machine, so I won't bother to add such a kludge.

**Comment by facelessuser** [comment]
This is without a doubt a race condition, most likely on wxpython's side. Unfortunately I'd have to debug wxpython to figure out what it is.  Most likely I'll have to file an issue, but as it is intermittent on the one machine it fails on, and I can't reproduce on my other windows machine, I doubt it would get much attention unless I could exacerbate the  problem with an ideal case that makes it reproducible.  Assuming I could figure that much out, I could most likely provide a workaround...oh well.

I'll continue to keep an eye out for anything that stands out to me as potentially troubling, but I'm not going to worry about this anymore.

**Comment by facelessuser** [comment]
I may just do something like:

```
if windows:
    wx.Exit()
```

It will at least for wx to close on exit before it goes off into the woods and create a segment fault.

**Comment by facelessuser** [comment]
It is looking like this issue is being caused by an application I have to use at work that somehow interferes. It is an application internal to our company, but when I close it, it appears Rummage no longer has an issue closing.  This explains why I can't replicate it on other systems.  So this probably isn't worth chasing down anymore.

**Comment by facelessuser** [comment]
Recent version, I've been having a really hard time reproducing this.

I had suspected this might be caused by leaky objects not getting cleaned up or a potential race condition in wxPython.  I usually try and suspect myself first, so I've been auditing the code fixing any leaky objects for the past month.  I think I've found all leaky objects, and with 4.0.1.

I'm yet to be able to reproduce this issue on 4.0.1, so it may be fixed now.  I'll keep an eye out, but if I can't reproduce this in the next couple of weeks, I'll consider this finally fixed.

**Comment by facelessuser** [comment]
I can't seem to reproduce this issue anymore, I'll consider this closed.

**Comment by ramanshsharma2806** [comment]
I am facing this on my Windows 10 machine. Just regular old python code I've been using that never had any problem (on this machine), now doesn't work when I downgraded python from 3.9 to 3.7 in the conda environment.

**Comment by facelessuser** [comment]
Are you using `pythonw -m rummage` or `python -m rummage`? I've been running Rummage on Windows 10 for years at this point, and I've not seen this issue anymore. I'd have to check how I'm running it myself as it isn't something I've thought about in a long time.

I will mention that I never run or test this in conda. All testing is done directly with Python on all platforms.
