### ISSUE TITLE
Check for Updates

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#161]
Add a command that will check PyPI for updates. We'll add a menu command that can make the request. Optionally we can add a setting to check daily, but disabled by default.

**Comment by klonos** [comment]
https://facelessuser.github.io/Rummage/changelog shows that there is a 4.x version available. Even if this is not stable yet, I would expect the "Include pre-releases" option in the preferences to show that version as available (tested using latest 3.6 final).

**Comment by facelessuser** [comment]
Depends what version of Python you are on. I suspect you're on 2. 4.0 is only on 3.4+.
