### ISSUE TITLE
Zip files

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#167]
This seems like something I'd actually use on occasion.  It'd be nice to be able to use the OSs file managers context menu to send files to an installed app, but as stated in another issue, that just sounds like more work than I want to do, but a simple Python method to archive/zip found files may be nice.

**Comment by facelessuser** [comment]
If I do this, it won't be for the next release.  We'll want to chunk the files as we zip them so you can abort without waiting for a super large file to finish, but that will require us to evaluate other 3rd party libs, or subclass from the base implementation and do our own.  Not interested in doing that right now.

**Comment by klonos** [comment]
...when I saw the title of the issue I assumed that it would be about allowing search **within** compresses files. Is this something that you'd consider?

**Comment by facelessuser** [comment]
Not sure about searching in a zip file. That can be slow, we'd have to chunk it as well...I figured sometime I may want to zip up some files from my search. It is pretty low priority. But, I'll at least think about searching in them. I won't promise this though.

**Comment by klonos** [comment]
Sure. It's just that as explained in the past, I come from Windows and http://dngrep.github.io (which I find to be the equivalent of Rummage) used to have this feature:

![dngrep](https://user-images.githubusercontent.com/2423362/40531893-06e9ac32-6041-11e8-98ed-37ab90a75329.png)

Thanks for considering

**Comment by facelessuser** [comment]
Considering this issue is now 2 years old, it's time to lay it to rest. If at some time in the future I feel differently, I can open a new issue, but clearly no work as occurred on this, and I have no immediate plans to do so either.

@gir-bot add S: wontfix
