### ISSUE TITLE
Expose a/the "stop" button in the "Files" tab.

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#222]
This is a follow-up to #140 ...it would be great to be able to stop the search without having to switch tabs.

If relatively easy and if you also think that it makes sense, perhaps add a "pause" button in there too(?).

PS: did I say thanks for all your hard work and time dedicated to this project? Thanks again 😄

**Comment by facelessuser** [comment]
Does hitting enter again stop it? I honestly don't remember and am not near a computer right now.

**Comment by facelessuser** [comment]
Yeah, I just hit enter again and it stops the search.  Enter starts it and can abort it.  Do you feel it's necessary to have a physical button?

**Comment by facelessuser** [comment]
I tested this on the latest 4.0 series.  This should work in 3.6...hopefully...I know I fixed an abort issue somewhat recently.

**Comment by facelessuser** [comment]
Hmm. This seems to only work on the search tab.  I'll have to adjust this shortcut.

**Comment by klonos** [comment]
Well, now that I know, this personally is not an issue for me any longer 👍 ...not sure if this is obvious.straight-forward for the newcomer user though. I am in general a fan of put-things-where-people-expect-to-find-them ...but up to you really.

**Comment by facelessuser** [comment]
The reason I never put the button was it was just weird to carry over replace and search on the result tabs and search tabs.  Or at least that is how I felt at the time.  Maybe something like escape would be more intuitive to stop. I mean I could carry the button over, but I feel it would just eat space from the results window...let me think about it.

**Comment by facelessuser** [comment]
Thinking about this, I'll look into adding a stop button that shows when a search is taking place. Once the search is stopped, we'll just hide it.

Enter usually starts a search on the main tab, but it'll also stop one that is running. I may change this to escape on all tabs as I feel that may make more sense.

**Comment by facelessuser** [comment]
I decided on just enabling escape key termination. FWIW, the escape key is enough.  This has been back ported to the 3x series and it has been applied to the 4x series as well.

**Comment by facelessuser** [comment]
Just to clarify, the escape key termination of search will be available from any tab.
