### ISSUE TITLE
How to install 4.x on Mac OS?

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#223]
I would like to offer to help with testing the upcoming 4.x release. Is there any easy way to install it currently? `pip2 install --upgrade rummage` only seems to take it up to 3.6.

**Comment by facelessuser** [comment]
Are you on Python 2?

**Comment by facelessuser** [comment]
Latest release requires Python 3.4+. Python 2 GUI had some issues with Unicode. I got tired of trying to hack around all the issues. A lot of Unicode stuff for fixed in latest release.

**Comment by klonos** [comment]
Yes, I am on python 2.7.10. I understand that there are issues with outdated versions of software, but I cannot currently update to python3 as this is my work laptop and it might mess my local. I will stick to Rummage 3.x for now.

Thanks for your help. Closing this ticket.

**Comment by facelessuser** [comment]
The Python 2 issues were getting harder to work around.  Unfortunately since Python 2 only has a year and a half before end of life, it was just a bit much to spend my free time fighting this when I use Python 3 everywhere and Python 2 is quite soon to be unsupported by Python itself.  Maybe in the future you can install them side by side.  I'm not sure if I plan to do anymore 3.x releases.

Hopefully 3.x isn't too bad compared to 4.0.  If there are some lingering bugs that were fixed in 4.0, maybe I can do some bug fix releases.

**Comment by facelessuser** [comment]
I looked over the fixes on the 4.x branch, and I will most likely backport recent fixes over to it. The main thing 4.x introduced is dripping of Python 2. Most everything else was bug fixes. I can't promise I'll backport new stuff to the 3.x, but I will try to update with bug fixes at least to Python2 end of life in 2020. I will probably address #222 on the 3.x branch as well. There are will still be some Unicode issues on the 3.x branch, but those likely won't go away. WxPython on Python 2 just doesn't play nice in many ways.

The easiest way is to just branch the main and revert Python 2 removal and set it up as the main branch. Bug fixes moving forward will need a backport issue as well if they are relevant to the 3.x branch.

**Comment by facelessuser** [comment]
All fixes that were available in 3.7 is released with a lot of the fixes from 4.x series.

**Comment by klonos** [comment]
Hey @facelessuser 👋 ...sorry to reopen this, but I was wondering if you have any pointers as to how to install the latest 4.x on Mac OS given that Python 3 can be installed via brew.

The problem is that brew can install both 2.x and 3.x at the same time, but 2.x is the default (although there is a request to switch to 3.x as the default here: https://github.com/Homebrew/homebrew-core/issues/7551). This effectively leaves most Mac users with rummage 3.x, which as is my understanding has stopped receiving further development.

As it is now, I have both 2.x and 3.x on my system:

```
python -V
Python 2.7.15

python3 -V
Python 3.7.2
```

...but as you can see, I need to use `python3` to invoke 3.x. Is there any way to support installing rummage 4.x in systems where both versions of python are installed, and automatically run it using python 3.x?

Thanks in advance for considering this.

**Comment by klonos** [comment]
...I have tried switching python, but it does not seem to work for me:

```
brew switch python 3.7.2_2
Cleaning /usr/local/Cellar/python/3.7.2_2
24 links created for /usr/local/Cellar/python/3.7.2_2

python -V
Python 2.7.15
```

**Comment by facelessuser** [comment]
`python3` or `python3.7 -v`?  I personally install Python 3 from the download link here https://www.python.org/downloads/release/python-372/, but that is just me 🤷‍♂️ . Doing it this way usually symlinks `python3` to the latest Python3 that you've installed, and then also creates a link to `python3.X`.  

If that doesn't work, you may need to symlink your Python to `/usr/local/bin` as `python3` and possibly `python3.7`.

After installing Python 3 you may want to take note of this

> There is a small issue on macOS with Python 3.6+: Python 3.6 changed how it gets the default certificates required to properly check URLs. The details are actually documented here: https://bugs.python.org/issue28150#msg276516.
>
> To get access again to the default certificates is actually quite easy. Assuming that Python 3.6+ was installed using the macOS installer from Python.org, you just need to navigate to /Applications/Python 3.6/Install Certificates.command and double click the command. The script will use pip to install certifi and creates a symlink in the OpenSSL directory to certifi's installed bundle location. If you are using something like macports, then you'll probably have to research to find out how to do the same thing.

**Comment by klonos** [comment]
> python3 or python3.7 -v?

`python3 -v` works for me, while `python3.7 -v` spits a whole series of messages and gets me into python mode.

Point is that I can run both `python` and `python3` on my system. Is there any way that you can make rummage detect this situation where both versions are installed/usable, then allow installation/upgrade to rummage 4? Just wondering.

**Comment by facelessuser** [comment]
Rummage doesn't upgrade itself, it only detects if there are new versions. I rely on pip to perform the upgrade, and I currently rely on the user to run that when *they* wish to upgrade. If someone came up with a clever way that was easy to maintain, I would possibly consider allowing Rummage to upgrade itself, but first time installation would need to be done through pip.

**Comment by facelessuser** [comment]
Closing this as the original question has been answered.
