### ISSUE TITLE
Provide a way to view which files were skipped

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#224]
As it is currently, there is only an indication of how many files have been skipped, but no way to see which ones. I am not sure what would be the best way to implement this UI-wise though.

**Comment by facelessuser** [comment]
Keep in mind, it shows only skipped files in folders it traversed. Folders it skipped, we don't tally files.

I think I do bubble up skip records. I'm not really sure what to do with them UX wise. I've never really cared about skipped files though. Displaying more files takes away from search speed though. I search huge projects, and not sure I personally want to eat up UI refresh with unnecessary files... Something to think about though.

**Comment by klonos** [comment]
OK, perhaps I don't fully understand how file/folder skipping works. What I meant to say is that, as a user, when I see a "Skipped 3", I need some way to know what was excluded from the results. Perhaps I need to change permissions in order to allow the skipped files/folders to be accessed? ...perhaps I need to "manually" search the skipped objects? ...not sure.

Thanks for taking the time to respond.

**Comment by facelessuser** [comment]
> when I see a "Skipped 3", I need some way to know what was excluded from the results.

But do you?  I mean, for me it was just numbers to let you know it was busy.  Just fun information while you're waiting for all the results to come in.  We don't list the filenames we did search but found no results.  The idea is to show you what you are looking for, not what you're not looking for.

If you want to see what was skipped, just do an inverse search.  So if I search for all python files `*.py`, then I could just search the inverse `-*.py`.  If you just want a list of files, don't include a search pattern and only include the file pattern.  Rummage will just list files without searching the content when you have a file pattern, but no search pattern.  Basically all this information can easily be obtained if you really want it already.

**Comment by facelessuser** [comment]
Hmm.  Looking at the 4.0 log, it looks like I tweaked behavior for wildcard patterns to act more sane.  Maybe that can get back ported to 3.x.  But you should be able to get the same thing on 3.6 with something like `*.*|-*.py`.  I think exception behavior used to require something to apply the exception to.  In 4.0 it works more like an inverse pattern.

**Comment by facelessuser** [comment]
With the `3.7` release, I think it should be easy enough to do a quick inverse file search (with no text search pattern) to ascertain which files were skipped. Inverse search would even be better as you could invert your folder exclude filters and it would also display content in folders that would have been skipped.

FWIW, I don't really want to waste cycles digging into skipped folders and populating and refreshing a list in the GUI.  I work in projects with thousands of files, so excluding thousands of files from display keeps things snappy.
