### ISSUE TITLE
Cannot install on Ubuntu 18.04

### ISSUE THREAD

**Issue by andrewdbate** [facelessuser/Rummage#245]
Firstly, for Ubuntu 18.04 LTS, the list of packages required is incorrect in the [installation instructions](https://facelessuser.github.io/Rummage/installation/).

The packages `python3.5-dev` and `libgstreamer-plugins-base0.10-dev` have been replaced by newer versions in the repositories.

Then, when I run `pip install rummage` or `sudo pip install rummage` it fails with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError
```

**Comment by facelessuser** [comment]
Documentation notes this can get out of date. It's difficult for me to keep up to date to the latest.

Is your setuptools and pip up to date?

**Comment by andrewdbate** [comment]
Yes, all packages are up to date using the latest versions from the Ubuntu 18.04 repositories, and all on a fresh install of Ubuntu.

**Comment by facelessuser** [comment]
Can you tell me what version of pip and setuptools is installed?

**Comment by facelessuser** [comment]
FYI, I unfortunately don't have dedicated Linux testers, and I am actually out of town for two weeks, so I won't be near a Linux box in that time. I suspect this is an outdated setuptools out pip issue, but if it isn't, it'll have to wait til I am in a Linux box and can upgrade to to the layers Ubuntu LTS.

**Comment by andrewdbate** [comment]
Here are the versions reported in the console:
```
andrew@ubuntu:~$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
andrew@ubuntu:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
andrew@ubuntu:~$ setuptools
setuptools: command not found
andrew@ubuntu:~$ setuptool
setuptool: command not found
andrew@ubuntu:~$ setuptools
setuptools: command not found
andrew@ubuntu:~$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__ 
'39.0.1'
>>> quit()
andrew@ubuntu:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__ 
'39.0.1'
>>> 
```

Would of the following commands should I be using to install Rummage?
```
pip install rummage
```
or
```
pip3 install rummage
```
The original error is a result of the first command as originally reported, but I just tried the second command to see what would happen (I'm not an experienced python user) and I get a different error.

**Comment by facelessuser** [comment]
Most likely pip is Python 2? While pip3 is Python 3. Using apt to install pip etc. will most likely give you an old version. It looks like your pip is outdated. I haven't verified setuptools yet. Personally I'd focus on installing rummage on Python 3, but that is up to you, but you'll need the lastest pip and setuptools and you'll need to make sure the WxPython dependencies for that Python version is installed.

**Comment by andrewdbate** [comment]
I can't get rummage to work on Mac OS High Sierra either.... Should I open another issue?

**Comment by facelessuser** [comment]
I have rummage working on Mac. Again, make sure pip and setuptools is up to date. I personally don't use the built-in Python on Mac, but install Python 3 directly from the official site.

**Comment by facelessuser** [comment]
FYI, some things changed with PyPI which is why I am strongly encouraging the latest pip and setuptools.

**Comment by andrewdbate** [comment]
Thing is, on the Mac I do have the latest versions of pip and setuptools:
```
AndrewsMac:test andrew$ pip3 --version
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
AndrewsMac:test andrew$ python3
Python 3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'39.2.0'
>>> 
```
However I still get an error when I try to run Rummage on the Mac:
```
AndrewsMac:test andrew$ rummage3.6
Traceback (most recent call last):
  File "/usr/local/bin/rummage3.6", line 7, in <module>
    from rummage.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/rummage/__main__.py", line 28, in <module>
    from .lib.gui.app import rummage_app
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/rummage_app.py", line 24, in <module>
    from .custom_app import PipeApp
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/custom_app.py", line 29, in <module>
    import wx
  File "/usr/local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so
  Reason: image not found
AndrewsMac:test andrew$ rummage
Traceback (most recent call last):
  File "/usr/local/bin/rummage", line 7, in <module>
    from rummage.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/rummage/__main__.py", line 28, in <module>
    from .lib.gui.app import rummage_app
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/rummage_app.py", line 24, in <module>
    from .custom_app import PipeApp
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/custom_app.py", line 29, in <module>
    import wx
  File "/usr/local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so
  Reason: image not found
AndrewsMac:test andrew$ python3 -m rummage
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rummage/__main__.py", line 28, in <module>
    from .lib.gui.app import rummage_app
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/rummage_app.py", line 24, in <module>
    from .custom_app import PipeApp
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/custom_app.py", line 29, in <module>
    import wx
  File "/usr/local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by facelessuser** [comment]
I literally have it installed on Python 3.6 on Mac. But I'm not in High Sierra, but I don't think that is the issue. What happens when you try to install WxPython directly?

**Comment by andrewdbate** [comment]
I'm not sure what you mean by "install WxPython directly".

However, when I run:
```
pip3 install -U wxPython
```
I get this:
```
AndrewsMac:test andrew$ pip3 install -U wxPython
Requirement already up-to-date: wxPython in /usr/local/lib/python3.6/site-packages (4.0.2)
Requirement not upgraded as not directly required: PyPubSub in /usr/local/lib/python3.6/site-packages (from wxPython) (4.0.0)
Requirement not upgraded as not directly required: six in /usr/local/lib/python3.6/site-packages (from wxPython) (1.11.0)
```

**Comment by andrewdbate** [comment]
Also, for completeness:
```
AndrewsMac:test andrew$ pip install -U wxPython
Requirement already up-to-date: wxPython in /usr/local/lib/python2.7/site-packages (4.0.2)
Requirement not upgraded as not directly required: PyPubSub in /usr/local/lib/python2.7/site-packages (from wxPython) (4.0.0)
Requirement not upgraded as not directly required: six in /usr/local/lib/python2.7/site-packages (from wxPython) (1.11.0)
Requirement not upgraded as not directly required: typing in /usr/local/lib/python2.7/site-packages (from PyPubSub->wxPython) (3.6.4)
```

**Comment by facelessuser** [comment]
Your error makes it look like WxPython isn't installed properly... What happens if you run

```
python3.6 -m rummage --debug --no- redirect
```

**Comment by andrewdbate** [comment]
The output is this:
```
$ python3.6 -m rummage --debug --no-redirect
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rummage/__main__.py", line 28, in <module>
    from .lib.gui.app import rummage_app
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/rummage_app.py", line 24, in <module>
    from .custom_app import PipeApp
  File "/usr/local/lib/python3.6/site-packages/rummage/lib/gui/app/custom_app.py", line 29, in <module>
    import wx
  File "/usr/local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so
  Reason: image not found
```
Also, for background, this is a fresh install of macOS High Sierra, and python3 etc was installed via homebrew.

**Comment by facelessuser** [comment]
Hmm. I'm not using Homebrew, and it definitely looks like something is wrong with WxPython. If you open a Python 3.6 session and run

```
import wx
```

What do you get?

**Comment by andrewdbate** [comment]
Yea... I get an error:
```
$ python3.6
Python 3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.6/Python
  Referenced from: /usr/local/lib/python3.6/site-packages/wx/_core.cpython-36m-darwin.so
  Reason: image not found
>>> 
```
I'll try to debug this. Maybe a feature request for Rummage is that it is packaged as a standalone app for Mac? ;-)

**Comment by facelessuser** [comment]
I work unusual WxPython, and try to install again. If this is still an issue, file an issue on the WxPython Phoenix repo on GitHub. This is not a direct rummage issue in Mac, simply a WxPython install issue.

**Comment by facelessuser** [comment]
If you get some time in the future, I'd try the official install path for Python 3 (non Homebrew).

Sorry it didn't work for you. All of these alternative install paths for Python are difficult to keep up with. If I get a chance, I'll take a look, but so far it looks like an upstream issue with WxPython.

**Comment by andrewdbate** [comment]
For others who come accross this thread, it does work on High Sierra if you uninstall python3 using homebrew (brew uninstall python3), and then download Python 3 from Python.org and install that package. I didn't manage to find a solution for Ubuntu 18.04.

**Comment by facelessuser** [comment]
Thanks for the info, and glad you got it working on Mac. I'll verify the last Ubuntu I tested on and will verify necessary steps to get it installed for the latest. Probably after my vacation, so about two weeks.

99% of the times install issues are related to wxpython as it is the most complex dependency to install, and no wheels are provided for Linux. All the base rummage code is pure Python which has no real install issues.

**Comment by facelessuser** [comment]
I've marked this as a documentation update.

1. We need to document better wxPython issues.  Homebrew is documented [here](https://facelessuser.github.io/Rummage/installation/#running-in-homebrew-macos), but at the time it had worked for me.  But others have generally reported some issues with homebrew and wxpython.  I need to dig into this a bit more and clearly define if it works, and if so, how you can reliably get it to work.

2. Linux is a big pain in regards to keeping documentation on how to get it to work.  WxPython has no Linux wheel, so it must compile it locally.  Unfortunately, new Linux distro versions can change the requirements, not to mention every Linux distro can have different requirements.

    Recent PyPI changes also frustrate this process as some Linux distros provide packages for pip that are old and don't quite work right with the latest PyPI changes.  I at least need to document that users need at least version X of pip and setuptools.

    Anyone using Linux general understands that some things require extra to work to install stuff as that is the nature of Linux.  But we should probably put even more emphasis to check out the official wxPython resources to figure out installation before trying to run `pip install rummage`.

It may be possible in the future to provide pre-packaged binaries in addition to pip.  At least for Windows and macOS this may make since.  This makes less since for Linux though as creating a common binary/package is near impossible.

**Comment by andrewdbate** [comment]
An idea about packaging on Linux: You might be able to use a snap package. (Even Spotify now does this.) But I don't not much about this. It would still be nice to have a package, even for Linux, or know that it would work on the latest Ubuntu.

**Comment by facelessuser** [comment]
Only because it's just me does it make it tough. I know it will work on Ubuntu, I just have to figure out the new magic recipe.

I'd love to package it, but the maintance cost goes up for me if I do. If it's easy enough, maybe. I'm leaving it open to see.

**Comment by facelessuser** [comment]
Attempting to install on Ubuntu 18.04 was a success.

So here are some notes:

- I did not, and would not generally try to use Python2 for installation.  I used Python 3.  I leave investigation to install with Python2 up to the user as all new features and releases are targeting Python 3.
- `sudo apt-get install python3-pip` gives an older pip, I'd use the following to install pip instead:

    ```
    curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    ```
- I followed the instructions in the documentation after that.  But here are some additional things.
    - I always install wxPython first on Linux (by itself) to ensure there are no problems with it installing as it is the reason Rummage installs will fail. So I ran the following first (on my system, since I only had Python 3 installed, `pip` was for Python3.6)

        ```
        sudo pip install wxpython
        ```

    - I swapped out to dependencies like the documentation suggests you may need to. So I used `libgstreamer-plugins-base1.0-dev` and `python3.6-dev` as they are more appropriate for Ubuntu 18.04.

        ```
        sudo apt-get install python3.6-dev dpkg-dev build-essential libwebkitgtk-dev libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3 freeglut3-dev libgtk-3-dev libwebkitgtk-3.0-dev
        ```

    - I then ran:

        ```
        sudo pip install rummage regex cchardet
        ```

For me there were no surprises.  Using the latest pip may be a factor and maybe is the only *surprise* that maybe is present.

Documentation instructs to use the correct Python version, but I guess doesn't cover the possibility of needing to use libstreamer 1.0 under Ubuntu.  It is referenced under Fedora, but the documentation also instructs the user to look at https://github.com/wxWidgets/Phoenix/blob/master/README.rst#prerequisites, to make sure you are using the latest, proper prerequisites.

I will look at making the documentation a little more clear for Linux. In general, it is best to install wxpython first to see if there are issues, and if there are, take that question to https://github.com/wxWidgets/Phoenix for instructions for your specific distro.  After wxPython is installed, Rummage should generally install without issues.

**Comment by facelessuser** [comment]
I will consider this answered, but feel free to discuss this further if you are still having issues after reading over my answer.
