### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#247]
Not sure if it's related to my specific OS (antergos KDE) or Rummage itself, but some settings are not saved on my system.

When using File >> Preferences, all the settings are saved perfectly. However, if I select/deselect any checkbox in main window (like "Create backups", etc.) they are only effective until Rummage is closed.

After Rummage is restarted, default options are used again. It drives me a bit crazy because I do not want to use case-sensitive search (which is default) and I do not want to create backups (which is default too). So every time I start Rummage, I must remember to manually uncheck these boxes.

Is it the expected behavior?

**Comment by facelessuser** [comment]
Those are only saved when used in an actual search.

**Comment by facelessuser** [comment]
Think of them as last used search options which are different from global preferences.

**Comment by toxpal** [comment]
Thanks, makes sense. I can live with it, especially when Rummage is the only worthy grepwin alternative in Linux world...

In other hand, would be great to have an option to remember last search settings in future releases...

**Comment by facelessuser** [comment]
My point is it **should** remember them once you've done a search. They aren't last searched until you do a search. If that setting is specifically getting missed in this scenario, please let me know.

**Comment by toxpal** [comment]
Yes, settings were not saved even after search. However, since you explained they should be saved, I rebooted system, performed some new searches, and everything is OK now. Did one more reboot to ensure settings are saved.

The issue is solved.
