### ISSUE TITLE
Investigate possible search focus issue on Linux

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#252]
Don't auto focus "Search in" field when coming back from Files or Content tab back to Search tab. When I view matches in Files tab and come back to Search tab, my only intention is to perform a new search (otherwise, I would just close Rummage after reviewing Files tab if I don't need to find new matches). Now, if I start typing some new match, it replaces "Search in" field. Sure, I can click TAB 2 times to go to "Search for" field or use a mouse, but it annoys a little, especially because I usually perform hundreds of searches a day. I think it would make more sense to auto-focus "Search for" field or don't focus any field at all.

Ref #249

**Comment by facelessuser** [comment]
This is another issue that needs investigation. This sounds like a GTK specific issue where when a tab control is selected, the first tab stop is selected automatically.  This seems to be specific to either GTK or maybe Linux or specific Linux distributions.  We may or may not provide a work around for this based on our results during investigation.  I don't really view this as a bug as much as maybe an annoyance for those on specific affected systems. I think this is an example of an OS or GUI framework trying to be helpful, but in an aggressive, annoying manner.

**Comment by toxpal** [comment]
It's good to hear you were able to re-produce this thing. So hopefully a workaround will be available one day...

**Comment by facelessuser** [comment]
It is low priority, but I plan to look into a solution.  I'll have to see if I can narrow things down to the exact event.

**Comment by facelessuser** [comment]
I think we have an actual fix for this in #260. It wasn't quite a straight forward as I hoped, but hopefully it is sufficient.  WxPython does have a tab change event, but it seems to occur before the GTK internal one, or there is simply some kind of race condition where we can't alter the focus while inside the wxPython change event.  Anyways, with an asynchronous, delayed call, it *appears* we are able to focus "Search for" instead.

The only thing I don't like about this solution is that we are hoping that 100 microseconds is a sufficient wait.  This could very depending on the system.  Maybe it is more than sufficient, maybe not, unfortunately I only have my system to test on.  Plus, I really wouldn't want to add a delay that is too long as that could introduce unexpected lag on focus and surprise people.  Hopefully, this is enough.
