### ISSUE TITLE
Make wiki multi-page

### ISSUE THREAD

**Issue by hadisfr** [facelessuser/Rummage#269]
What do you think about separating different parts of wiki and make it multi-page?

**Comment by facelessuser** [comment]
I honestly forgot we had the wiki enabled. Most likely it is out of date as all current documentation is hosted on GitHub pages.

With that said, people are free to delete redundant, useless data and restructure and add useful data as well.

**Comment by hadisfr** [comment]
I suggested it may be out of date. So updating it takes a significant amount of time and is not so effective. Perhaps someone else will do it later.

**Comment by facelessuser** [comment]
I will most likely delete the current docs.  The wiki is great for tips or tricks not explicitly already covered in the docs.  I will remove this information.

**Comment by facelessuser** [comment]
I went a head and deleted this information as it was currently not helpful in the context of current releases.  I've added a general note that it can be used for Rummage related things not covered explicitly in the docs.
