### ISSUE TITLE
Rummage 3.7.1 UI colors/contrast issues with Dark theme of Mac OS Mojave

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#306]
I have upgraded rummage via `pip install --upgrade rummage` from 3.6 to 3.7.1. Here's what the UI looks in Mac OS Mojave, with dark theme enabled:

<img width="876" alt="Screen Shot 2019-03-18 at 10 50 02 am" src="https://user-images.githubusercontent.com/2423362/54499949-f14a0880-496b-11e9-93bc-d508bfe7131d.png">

**Comment by facelessuser** [comment]
My mac is too old to update with dark mode.  I may have to test on my wife's mac. WxPython should handle this as I don't set the color to anything specific. Most likely this is a bug in wxPython.  There may be certain areas where I need to tweak something, like in the regex tester window, I think I use some preset colors there, but everywhere else should just use whatever the system reports.

What I would expect is that wxPython would just use the light theme regardless of dark mode setting until dark mode support is added to wxPython, but maybe that isn't the case. At least in your screenshot, it looks like the fonts and text input backgrounds respond to dark mode, while panel backgrounds and such do not. I suspect that wxPython uses native controls for some controls and custom controls for others.  So some seem to respond and others do not.

**Comment by facelessuser** [comment]
https://github.com/wxWidgets/Phoenix/issues/1132 related issue on wxWidgets/Phoenix.

**Comment by klonos** [comment]
Thanks for the very prompt response @facelessuser 👍 ...is there anything that needs to be done one your end, or just wait for this to be fixed upstream?

**Comment by facelessuser** [comment]
Not sure. I'm upgrading my wife's mac to mojave just so I can replicate the issue, but I think wxPython 4.1.0 will introduce support for dark mode. At that point, if the UI (or just a part of the UI) is still broken, then I may need to perform some kind of fix on my end, but without proper support, I can't tell how much I need to fix vs wxPython.

**Comment by facelessuser** [comment]
Thinking about this, since we don't know when support will be available, I can probably add a workaround option that will force faulty controls to render with known good colors. Theoretically when dark mode is supported, you should be able to just turn off the workaround.

I probably won't be able to get around to this until after this month, but I'll look into it as soon as I free up some time.

**Comment by facelessuser** [comment]
Okay I went to look at this today.  I loaded up Rummage on my wife's computer that has Mojave. Then I turned on dark mode, but I'm having a difficult time getting the contrast issue. What version of wxPython are you using?  Can you go to `help > Support Info` and post the output here?

**Comment by facelessuser** [comment]
Also, which version of Python are you on, and how did you install it? I'm using the official installer for the latest 3.7 from Python. Did you install via brew?

**Comment by facelessuser** [comment]
The exact cause of this issue is still not quite understood. I know it is a real problem, but it appears a number of things have to line up just right. Maybe specific wxwidgets and wxpython and python? Maybe something else as well?

Unfortunately, until I'm able to reproduce, I can't target the affected GUI elements as I'm not able to test which ones are affected, and that I've corrected the issue. If I'm able to, I'll see if I can resolve. If wxPython 4.1.0 comes out before then, and fixes the issue, then we'll just make a note that 4.1.0 fixes the issue and close.

**Comment by facelessuser** [comment]
In the soonish to release 4.6.0, a lot of work went in to make sure, that when dark mode is supported in wxPython, colors will dynamically adjust properly. Unfortunately, I was never able to reproduce the issue described here with Python 3.7. Maybe it is specific to how Python is installed, maybe homebrew vs the official installer, but I'm not sure. I use the official installer personally.

I wish I could have properly reproduced this issue, but unfortunately, I could not.

At least with the 4.6.0, I am fairly confident that we will get sane colors in the official dark mode.

**Comment by klonos** [comment]
Thanks @facelessuser ...I have since tried again to install rummage 4.x, but I am faced with #127 ...still trying to work things out in order to move to the latest version.

**Comment by facelessuser** [comment]
So you are installing in Anaconda or Homebrew?

**Comment by klonos** [comment]
Homebrew. I have removed the brew-installed python, and tried the official installer of 3.7.3, but not getting anywhere close:

```
echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/greg/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/node_modules/.bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/greg/drush:/Users/greg/.pyenv/bin
```

```
python -V
Python 2.7.16
```

No joy unfortunately, so I am thinking to revert back to the brew-installed python + rummage 3.x 😞

**Comment by facelessuser** [comment]
```
python3 -v
```

Or 

```
python3.7 -v
```

**Comment by facelessuser** [comment]
The official installer installs Python along side the defaul.

**Comment by klonos** [comment]
I have managed to upgrade to rummage 4.x after all, and this is not an issue in that version. Feel free to close @facelessuser. Thanks for all your help and pointers 👍
