### ISSUE TITLE
Fresh Install of Rummage on Linux - libwebkit2gtk ImportError

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#309]
After running Rummage for almost a year, I did a fresh re-installation of Linux and Rummage today. That is to say, all the packages (wxpython, setuptools, etc., including Rummage itself) are the latest versions.

As usually, I did **pip install rummage**, which completed without a single error. However, trying to run rummage fails with this error:

```
$ rummage
notify-send 0.7.7
Traceback (most recent call last):
  File "/usr/bin/rummage", line 11, in <module>
    load_entry_point('rummage==4.3.4', 'gui_scripts', 'rummage')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/rummage/__main__.py", line 28, in <module>
    from .lib.gui.app import rummage_app
  File "/usr/lib/python3.7/site-packages/rummage/lib/gui/app/rummage_app.py", line 25, in <module>
    from .. import rummage_dialog
  File "/usr/lib/python3.7/site-packages/rummage/lib/gui/rummage_dialog.py", line 42, in <module>
    from .regex_test_dialog import RegexTestDialog
  File "/usr/lib/python3.7/site-packages/rummage/lib/gui/regex_test_dialog.py", line 31, in <module>
    from . import gui
  File "/usr/lib/python3.7/site-packages/rummage/lib/gui/gui.py", line 21, in <module>
    import wx.html2
  File "/usr/lib/python3.7/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

I'm running Manjaro (which is Arch-based). I'm not very sure if this error is OS related or something was changed in recent versions of Rummage, which causes this error now. My first try was to install libwebkit2gtk via OS itself, but I couldn't even find such package. Any suggestions here?

Like I mentioned, installation itself didn't contain any errors.

P.S. Also tried installing Rumage with --user option. Once again, installation completed perfectly, but exactly the same error was displayed when trying got actually launch Rummage. Did multiple reboots as well.

**Comment by facelessuser** [comment]
It sounds like you are missing a dependency dealing with `libwebkit2gtk`.

How did you install wxPython?  Did you do it manually, or is there a prebuilt wxPython that your distro provides that you can install?

**Comment by toxpal** [comment]
Installed it manually via Manjaro package manager.

**Comment by facelessuser** [comment]
In general, as long as the a disto's prebuilt wxPython fulfills Rummage's requirements, I've come to the point where I like to recommend the prebuilt opposed to trying manually install wxPython by figuring out all of its dependencies.

As I see you've mentioned you used the package manager, have you tired to install the `libwebkit2gtk` dependency? Or is it already present?

**Comment by facelessuser** [comment]
Quick search in google, maybe this thread will help? https://forum.manjaro.org/t/general-question-on-installing-missing-requirements/30965

**Comment by toxpal** [comment]
Actually, I only installed wxPython via package manager later, after installing Rummage itself. I did so because I thought Rummage installed wxPython. At least it displayed this during installation:

_Collecting wxpython>=4.0.1 (from rummage)..._

And then int installed wxPython. Since I couldn't use Rummage because of the error mentioned in my 1st post, I decided to install wxPython manually.

**Comment by toxpal** [comment]
Finally, I was able to find webkit2gtk package and installed it via package manager. Now, it returns a different error:

ModuleNotFoundError: No module named 'pkg_resources.extern'

My best guess is that I'll need to manually install packages one by one, run rummage command, check for error, find another missing package, and so on... Hopefully that will work.

I'm just not very sure why depending packages were not installed automatically this time......

**Comment by facelessuser** [comment]
Installation on Linux is always messy. If you just install Rummage, it will install wxPython but I don't know if it will always install it proper for your distro, and sometimes not at all as it might not have proper dependencies.

This is why I've come to the point where I suggest, if you are on Linux, that you install via your package manager.  I would uninstall all wxpython installations and use your distros. If it complains about a missing dependency, I would try to install that dependency.

Rummage itself is pure Python. There are no dependency issues there. Issues on Linux only arise when installing wxPython. It is possible that your distro has some issues with its wxPython package. Often such pacakges are maintained by 3rd parties, and so things can get out of sync. I would use your distros package manager and install it, and if that gives the same error, try to install that missing dependency.

I only test on Ubuntu.

**Comment by facelessuser** [comment]
> ModuleNotFoundError: No module named 'pkg_resources.extern'

Maybe try `pip install -U setuptools`.

**Comment by toxpal** [comment]
This one did the trick!!!

Strangely, I also re-installed setuptools via Manjaro package manager for 2 times with reboots (because I also had idea it might be the cause), but that didn't help. However, doing it via command line worked for some reason, and Rummage starts now.

Thank you for your super-fast help once again. I was afraid I'll need to switch to another Linux distro because I use Rummage daily for my work, so it's a vital piece of software for me.

**Comment by facelessuser** [comment]
Most packages I recommend using `pip`, `wxpython` is kind of an exception as I've run into support issues trying to help people figure out how to get it to properly install with `pip`.  Often installing `setuptools` with a distro's package manager can get you an older version, `pip` will get you the latest.  With `wxptyhon`, I don't currently care if people have the latest, it just has to work 🙂 .

> Thank you for your super-fast help once again. I was afraid I'll need to switch to another Linux distro because I use Rummage daily for my work, so it's a vital piece of software for me.

So glad to hear others find Rummage so useful. It was honestly a tool I wrote for myself, and figured I'd be the only one who ever used it. I use it daily as well and depend on it. It's nice to hear others have found a place for it in their workflow as well.

**Comment by facelessuser** [comment]
Closing as question was answered.
