### ISSUE TITLE
Fix timectrl color issues

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#330]
The current timectrl that we are using does not respect the system colors. Try using : https://wxpython.org/Phoenix/docs/html/wx.adv.TimePickerCtrl.html which may work better for us.

**Comment by toxpal** [comment]
Regarding time... I don't know if it's just my eyes, but I believe time font is different than all the other fonts - https://i.postimg.cc/50tMkhgd/rummage.png

It's slightly bigger, isn't it? Using 4.6.1

**Comment by facelessuser** [comment]
Yeah, it's pretty much a little bigger or a little smaller depending on the OS.  It looks like it is using a completely different font, notice the zero styles are different in your picture. It has always been that way because for some reason, the generic time control overrides a number of different things, such as system colors, and apparently font style.

I was recently using a Linux dark theme which made me notice that the colors didn't match, which is why the recent 4.6.1 release. I was so focused on getting the colors right, I didn't pay any attention to the font style. I have no idea why they change everything...sigh. I will definitely look into it as it bothers me as well.

**Comment by facelessuser** [comment]
Ugh, I thought just setting `useFixedWidthFont` to `False` would fix it, but I had to extract the font being used from other text controls and then update the font of the `TimeCtrl` objects.

Anyways, the next release should have this fix. I need to test it on Windows and Linux before releasing, but I'll probably get it out today. I have no other immediate plans for any other fixes or features.

**Comment by facelessuser** [comment]
Okay, it looks good in all platforms:

![2019-05-29 07_37_12-Ubuntu18 04  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/1055125/58561606-b1fa2c80-81e4-11e9-8cbf-445b7ba5de3e.png)

I'll the fix out this morning.
