### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/Rummage#340]
1. Time in Linux isn't always getting exactly the right color depending on the theme.
2. alternating row color in lists when using some themes on Linux can be awful. Maybe add option to turn off alternating row color?  Or dynamically color it ourselves?

**Comment by facelessuser** [comment]
1. Turns out, it is not so easy getting the exact color that gets used. I think this is because the Linux theme can then do some other stuff.  But, if we set the colors to `wx.NullColour` we'll get the original color.

**Comment by toxpal** [comment]
Well, I use it on Linux for a year, and never had a problem with colors since this was fixed - https://github.com/facelessuser/Rummage/issues/254

**Comment by facelessuser** [comment]
It depends on the theme. I noticed it as I've switched to a Linux workstation and work. The original issue is due to the fact that the time control manually sets up pre defined colors without taking into consideration the theme. By default, controls not manually overriding colors get the correct color. In the first fix, we were creating a text box and grabbing the background color and using that for the time control, but in the theme I was using, that color was off. Somehow the color we grabbed, was not the final color the text control used. It was dark, but not the right shade. Setting to NullColour actually clears the manual color of the time control and forces it to use the default, which gives a correct color. It's just an oddity if working with wxPython.

As far as alternating row colors in list controls, I  The color it picks works in the theme I'm using, but I find it a bit jarring and I want to turn it off.

**Comment by toxpal** [comment]
Don't know if I should open a new issue, but now I also noticed color issue on dark Linux theme. When I browse for files/folders, all files are almost invisible because of incorrect colors. Folders are visible - https://i.postimg.cc/sDSJhF7T/rummage.png

Only happens in Rummage browser, other apps display file colors properly.

**Comment by facelessuser** [comment]
What do you mean "Rummage browser"?  Do you mean when you select a folder as an input?  If so, I don't have any control over that as we simply call the wxPython directory picker, but I imagine what it is doing is that Rummage is only allowing you to pick a directory, so files are greyed out as they are not pickable. I assume the theme is giving them that color?

**Comment by facelessuser** [comment]
With that said, I did discover some general tabbed interface color issues with Linux which I will be fixing soon. Each platform handles tab interface styling a little different, in general, we don't really care about except for the fact that we have this custom collapsible controls whose background must match the the background of the parent panel.

One would think we could just say `panel.GetBackgroundColour()` and use that color for the collapsible panel background, and generally, you'd be correct, except with tabbed interfaces. Every OS handles this different.

- macOS overlays transparent layer that lightens or darkens the panel, and you can't get access to that, so we simulate it.
- Windows makes all the tabs white, which is jarring, so we paint the tabbed panels the same as normal dialogs.
- Linux GTK seems can result in weird contrasts (buttons the same color as the panel) if we do what we do in Windows, and we don't want to overlay a light or dark layer like in macOS.

Currently, we are treating Linux like Windows, but we really shouldn't, so that will be fixed in the next version.

**Comment by facelessuser** [comment]
As for the browser issue, I am almost certain files are harder to see due to the theme "greying" them out due to it being a directory picker window. In general, Rummage is used to search directories, but yeah, you can also paste a file name, or even pass one in from command line. I guess Rummage should allow picking a file or folder. I'll have to look to see if wxPython will allow me to have a picker that selects files or folders.

**Comment by facelessuser** [comment]
I want to say we use a directory picker because there is no easy way in wxPython to allow picker either...

**Comment by toxpal** [comment]
> Do you mean when you select a folder as an input? If so, I don't have any control over that as we simply call the wxPython directory picker, but I imagine what it is doing is that Rummage is only allowing you to pick a directory, so files are greyed out as they are not pickable.

Yes, I mean when I start browsing for files/directories inside Rummage. Your point about non-pickable files make complete sense, didn't even think about it.

I know colors come from theme, but since all other apps displayed colors "properly", I thought it's a problem with Rummage. But your explanation is very clear, thank you.

**Comment by facelessuser** [comment]
Yeah, from what I understand, it should be a native file/directory picker (depending on whether you are using a FilePickerCtrl or a DirPickerCtrl). I purposely avoided doing my own to take advantage of whatever features the native one offered, and to ensure it would be familiar. I generally don't mind that it doesn't select files as I rarely need to search just a single file. On the rare occasion that I do, I'm usually have a plugin in my editor call rummage with the file name, either that, or I just navigate to the directory and then manually append the file name.
