### ISSUE TITLE
Moving mouse over results hides number of matches

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#344]
Not very sure how to explain it, so I'll try with screenshots. This is how search results look right after launching search - https://i.postimg.cc/Pr6Jk3X6/1.png (notice number of matches in footer)

Once I move my mouse over any file in search results (which is obviously needed if I want to open file), number of matches in footer disappears and never comes back - https://i.postimg.cc/c4QqR6jf/2.png (notice how number of matches is replaced with latest file I moved mouse cursor over).

Can we do something about this?

**Comment by facelessuser** [comment]
Are you sure when you move off all items, it doesn't show again after a small amount of time?

With that said, we could have it time out if the item it is hovered over is still the last hovered item after x about of time as well.

**Comment by facelessuser** [comment]
I haven't tested on Linux yet, but the full path status is on a timer. If you stop moving the cursor for about a half second or so, it should show the count again. It works on Windows and macOS, so I assume it works on Linux as well, but stranger things have happened.

**Comment by facelessuser** [comment]
It's actually on a five second timer, so a half second is a gross exaggeration. Maybe we can decrease that time?

**Comment by toxpal** [comment]
Oh, it really works after 5 seconds! I never waited that long, so I didn't know about such trick. In my personal opinion, I don't see a reason why footer should be replaced with filename of file that user moves his mouse over (since the filename and path is displayed in results list anyways), but I guess you had some good reason for that.

**Comment by facelessuser** [comment]
Some times my window is small and I don't want to scroll to see the full path. So mousing over the item gives you the full path for a time. The behavior was modeled after the windows tool I used as inspiration for Rummage. I'm pretty sure this was it's behavior, I can't remember now. To be honest, 5 second is probably a bit excessive. Maybe something like 3 or maybe even 2 seconds makes more sense. Long enough to see what you are looking for, but it shouldn't linger too long.

**Comment by toxpal** [comment]
> Some times my window is small and I don't want to scroll to see the full path. So mousing over the item gives you the full path for a time

Makes sense.

> Maybe something like 3 or maybe even 2 seconds makes more sense. Long enough to see what you are looking for, but it shouldn't linger too long.

That would be nice. Or maybe display number of matches in footer as soon as mouse cursor is moved away from file in search results list. Whichever is easier to implement and makes more sense for you :)

**Comment by facelessuser** [comment]
I can check. Right now I call a timer status function. If it is easy enough to cancel the timed status on mouse out, then maybe we can do that. Worst case, I can lower the timeout.

**Comment by facelessuser** [comment]
This turned out to be pretty easy. We will do the following:

- Decrease timed status to 3 seconds
- When mousing out of result items, clear timed status
- When still in result items, but a valid index is not found, clear timed status (this basically means mousing over an area of the result list that doesn't have an actual result item).

**Comment by toxpal** [comment]
Sounds great. Thanks for such fast and prompt responses.
