### ISSUE TITLE
Suggestion: add column offset in Editor section

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#350]
I believe it's not a problem with Rummage itself, but a problem how some (or maybe all?) text editors treat column numbers. For example, I use Geany, so my command in Editor section of Rummage is:

`geany "{$file}" --line {$line} --column {$col}`

And here's the problem: Geany treats first symbol in the line as 0, and Rummage seems to treat is as 1 maybe? So let's say I have such line in file:

`this is a sample line`

If I search for word **sample** with Rummage and open matching file, cursor is positioned not before "**s**" (which I expect, because I searched for "_sample_"), but before "**a**".  

Hope I explained everything clearly enough. I tried changing `--column {$col}` into `--column {$col}-1` and `--column {$col-1}` but that didn't work.

**Comment by facelessuser** [comment]
Most likely I'll just add a new symbol `col0`. There should never be a starting column any different than 0 or 1, so we'll just add the zero based variant as an optional symbol.

**Comment by toxpal** [comment]
Won't it work the same as manually setting command line to:

`EDITOR_NAME "{$file}" --line {$line} --column 0`?

I tried and it surely sets cursor to position 0, but if I search for word "sample" (as per example above), it sets cursor before ford "this", not before word "sample". 

In other hand, I understand it might be difficult to add such offset, so current behavior (when cursor is set after 1st matching symbol, not right before it) is still much better than having cursor set exclusively at position 0 of each line.

**Comment by facelessuser** [comment]
No it wouldn't be the same. `col` is a variable that inserts the column that the found instance is  located and is one based.  `col0` would be a zero based version of that variable that inserts the column in a range offset by one which would start line numbers at zero not one.

**Comment by toxpal** [comment]
Oh, makes sense now.

**Comment by facelessuser** [comment]
I can't think of a reason we'd ever need an offset different than 1. And if there was an editor that offset columns different than 0 or 1, I wouldn't care to support that.

**Comment by facelessuser** [comment]
A workaround for now is to simply omit the column and rummage will just select the line and not columns.

**Comment by toxpal** [comment]
> I can't think of a reason we'd ever need an offset different than 1.

Absolutely. My initial idea was to allow change position by 1 (not more) when needed, maybe I didn't explain it clearly enough.

**Comment by facelessuser** [comment]
Okay, either way would accomplish the same thing. I'll think about what is more intuitive. Regardless of which way we choose, the syntax will be documented on the tab you set the option, so I imagine it will be fine either way.

**Comment by toxpal** [comment]
From my point of view, your idea of **col0** would be easier to explain in documentation and understand for user. Plus, I think it would be easier to implement.

**Comment by facelessuser** [comment]
That was my initial thinking too. While my current editor is one based for columns, I understand not all adopt this convention. With an offset of one being the only deviation, it just makes sense to just provide an explicit variable for that case.

**Comment by toxpal** [comment]
Just wanted to say a quick Thanks for implementing this feature in 4.7.0. It's very useful.

**Comment by facelessuser** [comment]
Np. Wish I had realized this was needed sooner, but better late than never :slightly_smiling_face: .
