### ISSUE TITLE
Custom search filter feature request

### ISSUE THREAD

**Issue by alrusdi** [facelessuser/Rummage#41]
For me personally Rummage is great because of GUI (Ubuntu default search behaviour is kinda strange and unusable for me).

Other great feature (and feature which differs Rummage from other search tools) can be custom search filter. It may be GUI for writing some script in python to decide if current file or folder is relevant to my search. It should expose some useful context variables like current search settings; path, contents, name, mode, dates of current file etc.
So i wrote some procedure which returns Boolean result. If result is True and other search conditions is matched selected criteria then current object treated as relevant for search and displayed as result.

**Comment by facelessuser** [comment]
As I am ditching all the packaging stuff and just planning on this being installed as a normal python module, the package limitations are no longer an issue.  Still not sure about the custom filters though.  I am trying to think of a real use case.

**Comment by facelessuser** [comment]
I am warming up to this idea now.  I think I may inject hooks and allow people to write plugins for it.  I imagine some hooks would be:

- Replace hook; more complicated programatic replaces
- Encoding hook;  maybe write some code to detect encoding in certain file types.  For instance, look at the first line in an XML to determine what encoding is set to.
- Validation hook; as suggested above.

I would probably require each plugin to be use a common entry point.  I guess I would need an interface so a user could enable/disable installed plugins.

I imagine this would be done post 1.0.0.  Right now I am working to get 1.0.0 out the door.

**Comment by facelessuser** [comment]
In the end, I think I am allowing replace plugins but that is it.  Validation a search is a bit more than I want to do, but you could essentially validate a search before replace with the new replace plugin functionality coming.

We will keep search fairly simple, you can perform a search or a search chain (new feature coming) and all results will be displayed. But on replace, you can use a replace plugin and could avoid replacing certain matches by validating the returned result as desired.

Essentially this allows you to validate a before replacing and even do more complex replaces that replace patterns could not handle.

This will be probably be the only hook I will add moving forward.

**Comment by facelessuser** [comment]
Replace hook will be in next version.  I will close this as I am essentially passing on filtered search results for now.
