### ISSUE TITLE
Manjaro: GUI broken after Python upgrade

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#436]
After today's OS upgrade (Manjaro KDE) Python was auto upgraded to 3.10.1. Right after upgrade, Rummage didn’t start, so I re-installed app. Doing so also automatically re-installed all the extra stuff like wxPython, Backrefs, etc), Now it works, but GUI is terribly broken - https://ibb.co/826PYkq (notice tons of empty space at the bottom - this is where all the options should be). If I move mouse cursor over empty space, some options appear for a second and then disappear again.

I found a post about upcoming 3.10 support (https://github.com/facelessuser/Rummage/issues/434) and wonder if this broken GUI is actually related to Python 3.10 or it's some other issue. Since my daily work greatly depends on Rummage, I hope Python 3.10 will be supported officially?

System info:

```
- Arch: 64bit
- Platform: linux
- Python: 3.10.1 (CPython)
- Rummage: 4.16.4 final
- WxPython: 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
- Backrefs: 5.2
- Bracex: 2.2.1
- Wcmatch: 8.3
- Chardet: 4.0.0
- cChardet: Version could not be acquired!
- Regex: Version could not be acquired!
- Filelock: 3.4.2
- Markdown: 3.3.6
- Pymdown Extensions: 9.1
```

**Comment by facelessuser** [comment]
I'm simply waiting for WxPython to officially support Python 3.10. They haven't had a recent release yet. I tried to install the most recent package on my mac using Python 3.10 a number of weeks ago but did not get through the build step. I also see that there is a confirmed build issue on Windows as well: https://github.com/wxWidgets/Phoenix/issues/2024.

As WxPython does not officially support Python 3.10 yet, Rummage does not either. Once there is a new WxPython release, I'll begin working through any visual issues. There has been a longer than usual for a new version of WxPython.

You might have to install Python 3.9 side by side with Python 3.10 and install Rummage under Python 3.9. It's not worth my effort to start trying to fix things under one platform to claim Python 3.10 ready if I have no hopes of being able to validate other platforms.

**Comment by toxpal** [comment]
Thanks for the explanation. Yes, I realize it makes no sense to start fixing all the things when WxPython doesn't support Python 3.10 yet. Will patiently wait for WxPython update then...

**Comment by facelessuser** [comment]
@toxpal, I was recently able to get Rummage up and running for Python 3.10 on my back. I discovered my brew installed Python 3.10 was just busted, but using the official installer, I was able to install things, but I did use the a wheel from the snapshots of wxPython.

There appear to be no Linux wheels that I see, but maybe you could try to install the sdist: https://wxpython.org/Phoenix/snapshot-builds/wxPython-4.1.2a1.dev5310+af8cca51.tar.gz.

Granted, it is an alpha build, so your mileage may vary. I'd be interested to see if Linux is still busted with this version, but I understand that you may not want to disrupt your workflow to try this out, especially if you have something already working for you.

I'm not currently looking to do any extensive testing with an alpha wxPython, but figured it was worth sharing if you really, really wanted to attempt to get Rummage running on 3.10.

**Comment by toxpal** [comment]
Thanks for the update. Yes, I realize there's no reason for you to rush and start experimenting with alpha releases and it's perfectly fine for me. Even if GUI is broken, I'm already used to it (the only thing which is important to me is that Rummage does its main job - finds/replaces text as it should).

I'm on Manjaro Linux and usually manually upgrading/downgrading a single component breaks lots of dependencies, but I have a spare laptop which I will try to use for testing.

**Comment by facelessuser** [comment]
So, I was able to build from source the snapshot of wxpython alpha for python 3.10 on Ubuntu 18.04 that I use at work. I was able to build and install it. Running it, I could see no visual issues. I am expecting that things should be okay when the official actual gets released based on the results.

With that said, it is possible maybe some newer version of a distro could have issues using later libraries or something. Now that I know how to go about the process, I should be able to test in a more recent VM.

**Comment by facelessuser** [comment]
@toxpal wxPython 4.2.0 has been released. Can you confirm whether that fixes your issues? My initial tests on linux seem to be fine, though they default Python is not 3.10 on my current VM, and I am on a Ubuntu . I don't think 3.10 should make a difference, and I seem to be able to run Rummage on 3.10 mac and Windows. I'm hoping the Python 3.10 compatible 4.2.0 fixes any issues you were having.

If you are still having issues with 4.2.0, I can look a little deeper, and maybe setup a VM. With a similar setup. I'm currently not seeing any real breaking, visual changes.

**Comment by toxpal** [comment]
Thank you very much for not forgetting about this issue. Unfortunately, the current version of wxPython is still 4.1.1 in Linux Manjaro repos, but I will check again in a week or so and will surely update this topic.

**Comment by toxpal** [comment]
I just upgraded to wxPython 4.2.1 today and the issue is still here. Not sure why...

**Comment by facelessuser** [comment]
Okay, I'll have to set up a more recent Linux VM then. I'm skeptical about it specifically being a Python 3.10 issue, but maybe it still is. It could be an issue with a later version of KDE (which I don't normally test) or a specific theme. It could be something else entirely.

I'll have to start setting up some VMs and figuring it out. Hopefully, it is not Manjaro specific, but I guess we'll see.

**Comment by toxpal** [comment]
No worries, I already got used to it... Not the best experience in the world, but at least it works, which is most important thing for me :)

**Comment by facelessuser** [comment]
Understood. Ideally, it should get fixed though. It's the one problem with Linux, there are so many fractured distros and frontends. I generally test on Ubuntu with Gnome. It's just a lot of different configurations to stay on top of, so unless someone expresses explicit issues with a specific configuration, I just don't often have time to go through all distros with various configurations, especially distros that wxPython doesn't auto-build wheels for and distros that don't already have repositories for the latest wxPython.

Hopefully, this isn't too difficult for me to set up and reproduce in a VM, but once I do, I imagine it shouldn't be too difficult to fix. I'll re-open this issue to track this work. I was hoping this was a general Python 3.10 issue, but it appears it may be more specific.

**Comment by facelessuser** [comment]
@toxpal Can you provide the Manjaro version you are using in case I need to specifically replicate the exact environment?

**Comment by toxpal** [comment]
Since Manjaro is a rolling release, I use the latest one. Go to https://manjaro.org/download/ and select "Plasma Desktop"

**Comment by facelessuser** [comment]
Okay, thanks

**Comment by toxpal** [comment]
Manjaro received another update (including Python  stuff) yesterday, and right after upgrade Rummage stopped working (file import errors, syntaxt errors, etc.).

So I had to uninstall Rummage, wxPython (4.1.1 was installed) and re-install everything. Right after re-installing wxPython (4.2 this time) and rummage, GUI works again! I even forgot how beautiful and powerful Rummage GUI is!

**Comment by facelessuser** [comment]
That's fantastic news!
