### ISSUE TITLE
how to run rummage?

### ISSUE THREAD

**Issue by pleomati** [facelessuser/Rummage#449]
after instalation on ubuntu 22.04

Installing collected packages: wcmatch, rummage
Successfully installed rummage-4.18 wcmatch-8.5

i cant run it

rummage
rummage: command not found

any solution?

**Comment by facelessuser** [comment]
In the past, rummage has usually been available via the command line after installation on many systems, but it is possible that the environment may not expose the command depending on the setup.

On a linux based setup, the most reliable approach is probably going to be something like one of the following ways:

```
python3 -m rummage
```

Or, if you have multiple python versions, and the default python is not the one that is exposed as `python3`, you can usually specify the exact Python version. So assuming I am using Python 3.11, I would use:

```
python3.11 -m rummage
```

This all of course assumes everything is installed properly, but I don't have enough information to know whether that is the case or not, so for now, I will just assume it is.

**Comment by pleomati** [comment]
i get this error 
ImportError: libpcre2-32.so.0: cannot open shared object file: No such file or directory

so i install 
sudo apt install pcre2-utils

and it work,thx.

**Comment by facelessuser** [comment]
Yeah, linux is always a bit of a moving target, so you sometimes you have to figure out what non-python dependencies are missing. Glad you got it working.
