### ISSUE TITLE
Wrong release version

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#465]
This is not a problem with software itself and it's old, but I'm reporting in case @facelessuser missed it. The last release, which is a bugfix, has a wrong version number 40.20.3 on Github (should be 4.20.3). Version number in rummage itself is displayed properly (4.20.3).

https://github.com/facelessuser/Rummage/releases/tag/4.20.3 - tag says it's 4.20.3, yet it also says 40.20.3 on the same page.

**Comment by facelessuser** [comment]
Thanks! Fixed.
