### ISSUE TITLE
Replace isn't working with Regex

### ISSUE THREAD

**Issue by sojusnik** [facelessuser/Rummage#467]
When using Regex for searching and replacing, then only searching works, but not replacing, f.i. use:

search:`(\[\[zotero://open-pdf/library/items/ML4WSJ8H\?page=\d+\|)°(\]\])`
replace:`test`
Options:
![grafik](https://github.com/user-attachments/assets/adc62927-973c-41be-a3bd-b20cfc4c47eb)

When replacing, this error message will appear:
```
/home/sojusnik/Downloads/test.txt
  File "/home/sojusnik/.local/pipx/venvs/rummage/lib/python3.12/site-packages/rummage/lib/rumcore/__init__.py", line 907, in search_and_replace
    text.append(self.expand_match(m))
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/sojusnik/.local/pipx/venvs/rummage/lib/python3.12/site-packages/rummage/lib/rumcore/__init__.py", line 690, in expand_match
    return self.expand(m)
           ^^^^^^^^^^^^^^
  File "/home/sojusnik/.local/pipx/venvs/rummage/lib/python3.12/site-packages/rummage/lib/rumcore/__init__.py", line 752, in <lambda>
    self.expand = lambda m, t=template: _parser.expand_template(t, m)
                                        ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 're._parser' has no attribute 'expand_template'. Did you mean: 'parse_template'?
```
Repeating this without a Regex search, with simple words, works fine.

Here's the sample txt attached, where the replacing should take place: [test.txt](https://github.com/user-attachments/files/17194502/test.txt)

Happens with v4.21 (installed via `pipx install --system-site-packages rummage`) on Ubuntu 24.04.

**Comment by facelessuser** [comment]
Hmm, I was running `regex` lib when I tested. I must have missed that there is a change in `re`. Let me take a look.

**Comment by facelessuser** [comment]
Found the issue. I've added some sanity checks to make sure we catch these things in the future as well.

**Comment by facelessuser** [comment]
A release was made.

**Comment by facelessuser** [comment]
Yeah, sorry about that. I was focused on basic functionality, I wasn't expected replace to break in this way 😅.
